# Generated by Django 2.1.2 on 2018-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('born', models.DateField(verbose_name='Birth Date')),
                ('died', models.DateField(verbose_name='Death Date')),
                ('biography', models.TextField(max_length=500)),
                ('period', models.CharField(max_length=100)),
            ],
        ),
    ]
