# Generated by Django 2.1.2 on 2018-10-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20181015_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='Comment'),
        ),
    ]
