# Generated by Django 2.1.2 on 2018-10-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20181015_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poemcontent',
            field=models.TextField(max_length=5000, verbose_name='Poem'),
        ),
    ]
