# Generated by Django 2.1.2 on 2018-10-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20181015_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Written'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='born',
            field=models.CharField(max_length=100, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='died',
            field=models.CharField(max_length=100, verbose_name='Death Date'),
        ),
    ]
