# Generated by Django 2.1.2 on 2018-10-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20181016_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='period',
            field=models.CharField(max_length=100, verbose_name='Period(s)'),
        ),
    ]
