# Generated by Django 2.1.2 on 2018-10-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20181016_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='born',
            field=models.CharField(help_text='Month Day, Year', max_length=100, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='died',
            field=models.CharField(blank=True, max_length=100, verbose_name='Death Date'),
        ),
    ]
