# Generated by Django 2.1.2 on 2018-10-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20181018_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Collection'),
            preserve_default=False,
        ),
    ]
