# Generated by Django 2.1.2 on 2018-10-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20181018_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poet',
            options={'ordering': ['name']},
        ),
    ]
